version: '3.8'

services:
  nitter-1:
    image: zedeus/nitter:latest
    container_name: nitter-1
    ports:
      - "8081:8080"
    environment:
      - NITTER_ACCOUNT_POOL=pool1
    restart: always
    # Resource limits for cost-efficiency
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  nitter-2:
    image: zedeus/nitter:latest
    container_name: nitter-2
    ports:
      - "8082:8080"
    environment:
      - NITTER_ACCOUNT_POOL=pool2
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  nitter-3:
    image: zedeus/nitter:latest
    container_name: nitter-3
    ports:
      - "8083:8080"
    environment:
      - NITTER_ACCOUNT_POOL=pool3
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
